### ISSUE TITLE
Do you have to declare entry components?

### ISSUE THREAD

**Issue by crh225** [johnpapa/angular-lazy-load-demo#1]
https://stackblitz.com/edit/github-gfvs5w?file=src/app/app.module.ts
 ☝️ forked and put on stackblitz.

The only way I could get it to work was to put the lazy components in the entrycomponents array and declarations array. Should this demo work without doing so?

Thanks!

**Comment by johnpapa** [comment]
No declarations nor entry components needed with this technique angular 9. I noticed some of the versions are not updated in that package file.
